# Generated by Django 4.2.1 on 2023-08-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasker',
            new_name='user',
        ),
    ]
